/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.CPokoj;
import java.awt.event.ActionListener;

/**
 *
 * @author Elżbieta
 */
public class DodajPokojeView extends javax.swing.JFrame {

    /**
     * Creates new form DodajPokoje
     */
    private ActionListener listener;
    
    public DodajPokojeView(ActionListener controler) {
        listener=controler;
        initComponents();
        inicializeListeners();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        liczbaOsob = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        liczbaPokojow = new javax.swing.JTextField();
        dodajPokoj = new javax.swing.JButton();
        OKbutton = new javax.swing.JButton();
        AnulujButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dodanePokoje = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Dodawanie pokojów");

        jLabel2.setText("Liczba osób w pokoju");

        liczbaOsob.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        liczbaOsob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liczbaOsobActionPerformed(evt);
            }
        });

        jLabel3.setText("Liczba pokojów");

        liczbaPokojow.setText("0");

        dodajPokoj.setText("Dodaj");
        dodajPokoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajPokojActionPerformed(evt);
            }
        });

        OKbutton.setText("OK");
        OKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbuttonActionPerformed(evt);
            }
        });

        AnulujButton.setText("Anuluj");

        dodanePokoje.setText("Dodane pokoje:");
        dodanePokoje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(dodanePokoje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(257, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OKbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AnulujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(liczbaOsob, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(liczbaPokojow))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                                .addComponent(dodajPokoj)))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liczbaOsob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liczbaPokojow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dodajPokoj))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKbutton)
                    .addComponent(AnulujButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void liczbaOsobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liczbaOsobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liczbaOsobActionPerformed

    private void dodajPokojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajPokojActionPerformed
        // TODO add your handling code here:
      /*  CMiejsceNoclegowe m=new CMiejsceNoclegowe(this);
        m.addPokoj();*/
    }//GEN-LAST:event_dodajPokojActionPerformed

    private void OKbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKbuttonActionPerformed

    private void inicializeListeners(){
        
        OKbutton.addActionListener(listener);
        dodajPokoj.addActionListener(listener);
        AnulujButton.addActionListener(listener);
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnulujButton;
    private javax.swing.JButton OKbutton;
    private javax.swing.JButton dodajPokoj;
    private javax.swing.JLabel dodanePokoje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox liczbaOsob;
    private javax.swing.JTextField liczbaPokojow;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the liczbaOsob
     */
    public int getLiczbaOsob() {
        return Integer.parseInt((String)liczbaOsob.getSelectedItem());
    }

    /**
     * @return the liczbaPokojow
     */
    public int getLiczbaPokojow() {
        return Integer.parseInt(liczbaPokojow.getText());
    }
    
    public void setdodanePokoje(int liczbaPok, int liczOsob){
        String oldText=dodanePokoje.getText();
        String html="<html>"+oldText+"<br>" +" - liczba pokojów: "+liczbaPok+"  liczba osób: "+liczOsob+"<html>";
        dodanePokoje.setText(html);

        
    }
 
}
